apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foodrush
  namespace: argocd

spec:
  project: default
  source:
    repoURL: "https://github.com/gitsohel1030/eks-devops-gitops.git"
    targetRevision: main
    path: k8s/foodrush

  destination:
    server: https://kubernetes.default.svc
    namespace: foodrush
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

 