apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-app

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - hpa-blue.yaml
  - hpa-green.yaml
  - pdb-blue.yaml
  - pdb-green.yaml


labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: web-app


patches:
  # blue image patch 
  - path: patch-blue-image.yaml    
    target:
      kind: Deployment
      name: web-app-blue

  # green image patch
  - path: patch-green-image.yaml
    target:
      kind: Deployment
      name: web-app-green

  # Default traffic route to
  - path: traffic/traffic-green-100.yaml
    target:
      kind: Ingress
      name: web-app-ingress
