apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kube-prometheus-stack
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.1.1
      helm:
        valueFiles:
          - $values/k8s/monitoring/values.yaml

    - repoURL: https://github.com/gitsohel1030/eks-devops-gitops.git
      targetRevision: main
      ref: values   # gitops repo aliased as $values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # telling argocd not to block on PVC health
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status/phase

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true