apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - blue-deployment.yaml
  - green-deployment.yaml
  - service-blue.yaml
  - service-green.yaml
  - ingress.yaml
  - hpa-blue.yaml
  - hpa-green.yaml
  - pdb-blue.yaml
  - pdb-green.yaml

# cluster wide labels
# labels:     
#   - pairs:
#       app.kubernetes.io/name: web-name
#   - pairs:
#       app.kubernetes.io/part-of: web-app  